apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
  namespace: graylog-demo
  labels:
    app: elasticsearch
spec:
  selector:
    app: elasticsearch
  clusterIP: None
  ports:
    - port: 9200
      name: restapi
    - port: 9300
      name: node2node