apiVersion: apps/v1
kind: Deployment
metadata:
  name: graylog
  namespace: graylog-demo
  labels:
    app: graylog
spec:
  replicas: 1
  selector:
    matchLabels:
      app: graylog
  template:
    metadata:
      labels:
        app: graylog
    spec:
      containers:
      - name: graylog
        image: graylog/graylog:6.1.8
        env:
        - name: GRAYLOG_PASSWORD_SECRET
          value: your_passwrod_secret
        - name: GRAYLOG_ROOT_PASSWORD_SHA2
          value: your_root_password
        - name: GRAYLOG_ELASTICSEARCH_HOSTS
          value: http://elasticsearch.graylog-demo.svc.cluster.local:9200
        - name: GRAYLOG_MONGODB_URI
          value: mongodb://mongo:27017/graylog
        - name: TZ
          value: Europe/Istanbul
        - name: GRAYLOG_ROOT_TIMEZONE
          value: Europe/Istanbul
        - name: GRAYLOG_TIMEZONE
          value: Europe/Istanbul
        ports:
        - containerPort: 9000
        - containerPort: 12201