apiVersion: v1
kind: Service
metadata:
  name: graylog-svc
  namespace: graylog-demo
spec:
  type: ClusterIP
  selector:
    app: graylog
  ports:
  - name: "ui"
    port: 9000
    targetPort: 9000
  - name: "log"
    port: 12201
    targetPort: 12201