apiVersion: v1
kind: ConfigMap
metadata:
  name: mongodb-config
  namespace: graylog-demo
immutable: false  
data:
  username: mongoadmin  
  mongodb.conf: |  
    storage:
      dbPath: /data/db  
    replication:
      replSetName: "repl-set"  # important!!